### ISSUE TITLE
UnhandledPromiseRejection after upgrade from 0.49.1 to 0.55.1 - crash NR

### ISSUE THREAD

**Issue by marc-gist** [zachowj/node-red-contrib-home-assistant-websocket#1030]
### Describe the bug

After upgrading NodeRed crashes last message in log is
```
8 Aug 07:51:48 - [info] [server:HA-Arena] Connected to https://xxx
8 Aug 07:51:48 - [info] [server:HA-Test] Connected to https://xxx
8 Aug 07:51:48 - [info] [server:HAHouse] Connected to https://xxx
8 Aug 07:51:49 - [red] Uncaught Exception:
8 Aug 07:51:49 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
```

### To Reproduce

Upgrade from 0.49.1 to 0.55.1
Have 3 connections to different HA servers

### Expected behavior

To work as usual

### This package's version (not the Home Assistant add-on version)

0.55.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.0.2

### Node.js version

16.16.0

**Comment by msmarks** [comment]
The UnhandledPromiseRejection is
```
Unhandled Rejection at: Promise {
  <rejected> { code: 'unknown_command', message: 'Unknown command.' }
}
```

stack trace is
```
[ Stacktrace altered by https://github.com/grantila/trace-unhandled ]
Unknown command.
    ==== Promise at: ==================
    at TraceablePromise.then (<anonymous>)
    at TraceablePromise.catch (<anonymous>)
    at refreshSwallow (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:815:49)
    at setupUpdateSubscription (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:834:13)
    at Object.subscribe (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:868:17)
    at subscribeEntityRegistryDisplay (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/collections.js:39:16)
    at Websocket._Websocket_haEvents (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:426:54)
```

**Comment by zachowj** [comment]
Are you running a version of Home Assistant before 2023.3.0?

**Comment by marc-gist** [comment]
> Are you running a version of Home Assistant before 2023.3.0?

I happen to be (one is 2022.7.2).  not sure about @msmarks 

It should still "fail gracefully" and not completely take out NodeRed :(
