### ISSUE TITLE
Errors/warning on deprecated API after upgrading to node-red 3.1.0

### ISSUE THREAD

**Issue by ingvarso** [zachowj/node-red-contrib-home-assistant-websocket#1051]
### Describe the bug
The followin errors appear in the log and in the GUI after upgrading to node-red 3.1.0.

```
8 Sep 16:43:16 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
8 Sep 16:43:16 - [warn] Error
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at CallService.evaluateJSONata (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
    at CallService.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
    at CallService.preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at callServiceNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at callServiceNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at callServiceNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:494:10)
```
### To Reproduce

Running on node-red 3.1.0

Looks like it is happening when the "call-service" is triggered.

### This package's version (not the Home Assistant add-on version)

0.56.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.1.0

### Node.js version

16.20.2

**Comment by chriswood1001** [comment]
My Node-Red debug window is flooded with these every few seconds making it unusable. I'm forced to temporarily role back Node-Red until this is addressed.

**Comment by zachowj** [comment]
Duplicate #898
