### ISSUE TITLE
Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback.

### ISSUE THREAD

**Issue by AndreKR** [zachowj/node-red-contrib-home-assistant-websocket#1058]
### Describe the bug

Using a _call service_ node in Node-RED 3.1.0-beta.4 shows a warning in the debug panel: 
```plain
Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.

Error
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at CallService.evaluateJSONata (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
    at CallService.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
    at CallService.preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at callNextHook (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:193:13)
    at callNextHook (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:215:17)
    at invokeStack (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:237:5)
    at Object.trigge...
```

### This package's version (not the Home Assistant add-on version)

0.56.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.1.0-beta.4

### Node.js version

v16.20.1

**Comment by zachowj** [comment]
Duplicate #898
