### ISSUE TITLE
Depracation warning with latest node-red (3.1)

### ISSUE THREAD

**Issue by carefulcomputer** [zachowj/node-red-contrib-home-assistant-websocket#1071]
### Describe the bug

When starting latest node-red (3.1) I see following warnings (repeated multiple times) in log

```
24 Sep 16:20:17 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
24 Sep 16:20:17 - [warn] Error
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at TypedInputService.getValue (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/TypedInputService.js:58:85)
    at /data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/OutputController.js:53:50
    at Array.forEach (<anonymous>)
    at CurrentStateController.setCustomOutputs (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/OutputController.js:52:20)
    at CurrentStateController.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/current-state/CurrentStateController.js:58:14)
    at CurrentStateController._InputOutputController_preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/InputOutputController.js:61:76)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at currentStateNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at currentStateNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at currentStateNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:494:10)
    at deliverMessageToDestination (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:799:40)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:815:21)
    at processImmediate (node:internal/timers:466:21)
```

### To Reproduce

Install node-red 3.1. 
Install websocket plugin
create a flow which uses this plugin
Start node-red

### Expected behavior

No depracation warking

### Screenshots

<img width="1464" alt="image" src="https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/3331518/35854285-e08b-47a4-a483-f6bbe3897203">

### This package's version (not the Home Assistant add-on version)

0.56.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.1

### Node.js version

v16.20.2

**Comment by zachowj** [comment]
Duplicate #898
