### ISSUE TITLE
Deprecated API warning

### ISSUE THREAD

**Issue by 199Kay** [zachowj/node-red-contrib-home-assistant-websocket#1090]
### Describe the bug

When I use a device via Jasnato I get the following message:

`Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.`

`Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at CallService.evaluateJSONata (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
    at CallService.onInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
    at CallService.preOnInput (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
    at /opt/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/opt/node_modules/@node-red/util/lib/hooks.js:166:13)
    at callServiceNode.Node._emitInput (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at callServiceNode.Node.emit (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at callServiceNode.Node.receive...`

### To Reproduce

Create an inject node, 
then a call service,
Domain light, service trun_on
Device for me was e.g. light kitchen
and then under Data a JASONATA :
`{	   "brightness":250,	   "transition":0.5 	}`

And finally Deployen and after the manual triggering of the flow appears the hint. 
It is independent of which function, as soon as a JASONATA is entered, it gets the hint.

### Expected behavior

The light should turn on with a transition of 0.5 to the brightness 250. This makes it even without problems.

### Example Flow

```json
[{"id":"300dc8b354cd1292","type":"inject","z":"3c34ee1d6c03432a","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":560,"y":1020,"wires":[["fbecad68285423b8"]]},{"id":"fbecad68285423b8","type":"api-call-service","z":"3c34ee1d6c03432a","name":"Dimm 250","server":"4d7e86b0.0ece08","version":5,"debugenabled":false,"domain":"light","service":"turn_on","areaId":[],"deviceId":["47ab84c01146956d34d547bcd1146949"],"entityId":[],"data":"{\t   \"brightness\":250,\t   \"transition\":0.5 \t}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":770,"y":1020,"wires":[[]]},{"id":"4d7e86b0.0ece08","type":"server","name":"Home Assistant","addon":true}]
```

### This package's version (not the Home Assistant add-on version)

0.56.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

3.1.0

### Node.js version

14.XX.XX

**Comment by GerdRuetten** [comment]
It's even easier to reproduce the warning
- Inject node
- Current State node
- Debug node

If you trigger an inject, you get the debug result, but immediately afterwards two warnings:

`"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."`

and

```
Error
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at JSONataService.evaluate (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
    at CallService.evaluateJSONata (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:131:36)
    at CallService.onInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/call-service/controller.js:63:50)
    at CallService.preOnInput (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/BaseNode.js:208:18)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at callServiceNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at callServiceNode.Node.emit (/usr/src/node-red/node_modules/@node-red/ru...
```

The error can be reproduced at any time.

Node-RED version
3.1.0

**Comment by zachowj** [comment]
Duplicate https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/898
