### ISSUE TITLE
Node red deprecated warnings

### ISSUE THREAD

**Issue by regevbr** [zachowj/node-red-contrib-home-assistant-websocket#1174]
### Describe the bug

Looking at the debug tab of node red, I see many errors:

```
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."
```

```
Error: 
    at Object.evaluateJSONataExpression (/opt/node_modules/@node-red/util/lib/util.js:775:18)
    at EventsAll.evaluateJSONata (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/controllers/BaseNode.js:264:30)
    at EventsAll.getTypedInputValue (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/controllers/BaseNode.js:295:32)
    at /config/node_modules/node-red-contrib-home-assistant-websocket/dist/controllers/BaseNode.js:341:32
    at Array.forEach (<anonymous>)
    at EventsAll.setCustomOutputs (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/controllers/BaseNode.js:340:20)
    at EventsAll.onHaEventsAll (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/controllers/EventsAll.js:37:18)
    at EventEmitter.emit (node:events:517:28)
    at Websocket.emitEvent (/config/node_modules/node-red-contrib-home-assistant-websocket/dist/homeAssistant/Websocket.js:33:30)
    at Websocket.onClientEvents (/config/no...
```

Seems they originate from your controllers/BaseNode.js file

### Environment Information

* diagnostic flows fails for me...

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.33.0
Stage | running
Available Repositories | 1351
Downloaded Repositories | 46
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 5, 2024 at 02:00
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-13.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 228.5 GB
disk_used | 107.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.8.17), Home Assistant Google Drive Backup (0.111.1), MariaDB (2.6.1), Mosquitto broker (6.4.0), Node-RED (16.0.2), Node-RED Dashboard (1.3.0), Plex Media Server (3.3.2), Studio Code Server (5.14.2), Transmission (dev), Zigbee2MQTT (1.33.2-1), Glances (0.20.0), InfluxDB (4.8.0), Grafana (9.1.1), pigpio (1.5.2), ESPHome (2023.11.6), MQTT Explorer (browser-1.0.1), Matter Server (4.10.2), room-assistant (beta) (3.0.0-beta.5), Silicon Labs Multiprotocol (2.3.2), Ring-MQTT with Video Streaming (5.6.3), go2rtc (1.8.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 33
views | 9
mode | storage

</details>

<details><summary>MiWifi</summary>

version | 3.0.0
-- | --
192.168.31.1 (R2350) | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 27, 2023 at 18:39
-- | --
current_recorder_run | November 28, 2023 at 11:26
estimated_db_size | 507.30 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by regevbr** [comment]
Got it thanks, I was sure it gets updated along the addon, but apparently not. Had to update a few more packages.
