### ISSUE TITLE
Intermittent "connection closed"; shows in log, does not generate an error in Node-red

### ISSUE THREAD

**Issue by bogorad** [zachowj/node-red-contrib-home-assistant-websocket#1225]
### Describe the bug

Suddenly I'm getting these messages in my NR log:

```
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connecting to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connected to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connection closed to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connecting to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connected to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connection closed to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connecting to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connected to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connection closed to http://localhost:8123
26 Dec 20:24:58 - [info] [server:ha-bruc-pi] Connecting to http://localhost:8123
```

Restarting HA does not help. Restarting Node-red helps, but there's no error generated in NR, so there's no way of knowing that something is wrong.

### Environment Information

Version: 

Home Assistant version: 2023.12.3
Companion version:

Node-RED version: 3.1.3
Docker: yes
Add-on: no

Node.js version:
OS:

**Comment by zachowj** [comment]
Check Home Assistant log. Increase the log level if nothing is shown at the time of disconnect.

**Comment by bogorad** [comment]
Thanks for responding! I found something notable - something about "token expired":

NR log:
```
25 Dec 12:04:12 - [info] Started modified nodes
25 Dec 13:31:49 - [info] [server:ha-bruc-pi] Connection closed to http://localhost:8123
25 Dec 13:31:49 - [info] [server:ha-bruc-pi] Connecting to http://localhost:8123
25 Dec 13:31:49 - [info] [server:ha-bruc-pi] Connected to http://localhost:8123
25 Dec 18:06:19 - [info] [server:ha-bruc-pi] Connection closed to http://localhost:8123
```
so it died at 13:31:49

HA log:
```
2023-12-25 13:28:39.010 INFO (MainThread) [homeassistant.components.fan] Setting up fan.miio_yeelink
2023-12-25 13:28:39.011 INFO (MainThread) [custom_components.miio_yeelink] Initializing with host 192.168.11.163 (token a00e6...)
2023-12-25 13:28:44.019 ERROR (MainThread) [custom_components.miio_yeelink] Device office-mi-fan unavailable or token incorrect: Unable to discover the device 192.168.11.163
2023-12-25 13:29:12.992 INFO (SyncWorker_6) [pychromecast] Quitting current app
2023-12-25 13:29:12.992 INFO (SyncWorker_6) [pychromecast.controllers] Receiver:Stopping current app 'E8C28D3C'
2023-12-25 13:31:44.063 INFO (MainThread) [homeassistant.components.fan] Setting up fan.miio_yeelink
2023-12-25 13:31:44.067 INFO (MainThread) [custom_components.miio_yeelink] Initializing with host 192.168.11.163 (token a00e6...)
2023-12-25 13:31:49.074 ERROR (MainThread) [custom_components.miio_yeelink] Device office-mi-fan unavailable or token incorrect: Unable to discover the device 192.168.11.163
2023-12-25 13:31:49.381 INFO (MainThread) [custom_components.nodered.discovery] Updating sensor ade7372eb001b8a7 5b869741b211d1c2
2023-12-25 13:31:50.037 WARNING (Thread-5 (_listen)) [homeconnect.sseclient] Exception while reading event: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 81, in __next__
    next_chunk = next(self.resp_iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/homeconnect/api.py", line 168, in _listen
    for event in sse:
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 91, in __next__
    self._connect()
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 81, in __next__
    next_chunk = next(self.resp_iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/homeconnect/api.py", line 168, in _listen
    for event in sse:
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 91, in __next__
    self._connect()
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 56, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/homeconnect/sseclient.py", line 81, in __next__
    next_chunk = next(self.resp_iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
2023-12-25 13:31:51.051 INFO (Thread-5 (_listen)) [homeconnect.sseclient] Connecting ...
2023-12-25 13:31:51.052 INFO (Thread-5 (_listen)) [homeconnect] Token expired in event stream.
2023-12-25 13:31:51.219 INFO (Thread-5 (_listen)) [homeconnect.sseclient] Connecting ...
2023-12-25 13:31:51.294 INFO (Thread-5 (_listen)) [homeconnect] Listening to event stream for all devices
2023-12-25 13:34:49.129 INFO (MainThread) [homeassistant.components.fan] Setting up fan.miio_yeelink
2023-12-25 13:34:49.130 INFO (MainThread) [custom_components.miio_yeelink] Initializing with host 192.168.11.163 (token a00e6...)
2023-12-25 13:34:54.138 ERROR (MainThread) [custom_components.miio_yeelink] Device office-mi-fan unavailable or token incorrect: Unable to discover the device 192.168.11.163
```

**Comment by zachowj** [comment]
The expired token is from home connect, not NR. If there was an error it would have been around `25 Dec 18:06:19` when NR was disconnected.

**Comment by bogorad** [comment]
> edit: Looks like the Device office-mi-fan is going offline at the same time. Are you having network issues?

nope, this device is physically disconnected (offline). but the extension seems to be constantly trying to revive it.

I'll increase the WebSocket log-level, thanks.

**Comment by bogorad** [comment]
> edit: Looks like the Device office-mi-fan is going offline at the same time. Are you having network issues?

nope, this device is physically disconnected (offline). but the extension seems to be constantly trying to revive it.

I'll increase the websocket log-level, thanks.

**Comment by pittbull** [comment]
any updates on this? Currently struggling with the same problem ...

**Comment by bogorad** [comment]
> any updates on this? Currently struggling with the same problem ...

Enabled websocket logging and lying in wait. So far hasn't happened again :)

**Comment by pittbull** [comment]
Happens every couple of minutes here but the websocket debug log is huge ...

**Comment by pittbull** [comment]
Browsing through my websocket debug log on HA I find these two lines which correlates with when Nodered disconnects:

```
2023-12-29 23:21:02.813 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [546908513984] nodered from 172.17.0.7: Writer done
2023-12-29 23:21:02.813 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [546908513984] node-red from 172.17.0.7: Disconnected
```

**Comment by pittbull** [comment]
From what I've gathered so far every 120 seconds Home Assistant peaks on CPU usage (100%) on four cores (I am temporarily running on a Pi4B due to main server being repaired). When this happens Nodered disconnects and the reconnects.

I have disabled all addons and services and HA still peaks on 100% every 120 seconds.

**Comment by pittbull** [comment]
On my end the culprit was a timed process which ate all my cpu power (as I am temporarily running on a limited rpi), which was not interruptible which lead to NR disconnecting. I found it my enabling debug logging and carefully watching what happened every 120 sec - as the process spat out huge logs (which also contributed to "locking up" HA). I removed the offending process - temporarily - and everything is back to normal.

**Comment by Veldkornet** [comment]
I also experience this every now and then, although I have an IntelNUC with HassOS, so I don't think COU is the issue for me...
Even so, why does it never recover?

**Comment by bogorad** [comment]
and it's back after update to 2023.4 and -red-contrib-home-assistant-websocket 0.63.1

maybe suggest a debugging tool that would help collect data so this can be fixed once and for all?

**Comment by donburch888** [comment]
In my case 
Whisper LOG shows my voice command “studied light on” then connection lost.
```
INFO:faster_whisper:Processing audio with duration 00:01.680
INFO:wyoming_faster_whisper.handler: studied light on
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:31> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 95, in handle_event
    await self.write_event(self.wyoming_info_event)
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 29, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.9/dist-packages/wyoming/event.py", line 131, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```
The NR Sentence node is not activated. 
Jarvis does not respond for a while, but I do not have any addon's Watchdog timer enabled. 

Curiously the LOG for Mosquitto Broker is showing disconnections from nodered at much the same time. 
```
2024-04-07 17:35:53: Client nodered_722316b578c76c08 disconnected.
2024-04-07 17:35:53: New connection from 192.168.1.98:52742 on port 1883.
2024-04-07 17:35:53: New client connected from 192.168.1.98:52742 as nodered_0408554e8e6f169e (p2, c1, k60, u'nodered').
2024-04-07 17:50:52: Saving in-memory database to /data//mosquitto.db.
```

**Comment by f1lint** [comment]
Same issue

**Comment by bogorad** [comment]
for the time being, I created a custom helper/timer in HA (30 seconds). I trigger it from NR, wait 60 sec for it to finish, and it it does not, I restart NR (via a webhook running on the host)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2777398/0b312a73-83bf-45f7-93eb-0cbd9020b4b0)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2777398/0bad5478-e433-40d9-9e57-06002247f19c)

**Comment by kars85** [comment]
@bogorad  - would you paste your flow json for that automation? Thanks for the help on a workaround. Stinks this isn't getting a fix.

**Comment by bogorad** [comment]
sure. I simplified it. now there's an "automation" in HA to trigger timer every 30 seconds, and all I have to do in NR is to wait for the timer to stop "starting" for 1 min.

![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2777398/d867380f-ea5c-4d44-9b50-54aee6f14f16)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2777398/94c2bd55-9291-4954-8177-6aaf230d8f2d)
![image](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/assets/2777398/b2f206da-2894-4f9d-8d5b-14a559c2adf1)


https://pastebin.com/V16vChpA

**Comment by zachowj** [comment]
Try updating to the latest release, v0.47.0, and see if it resolves the issue.

**Comment by Veldkornet** [comment]
Not sure that there's any evidence to prove that this is no longer an issue

**Comment by teetot-aq** [comment]
![image](https://github.com/user-attachments/assets/c910e9b2-3d85-46e5-b7f4-ae6f39515a2c)

Enabling heartbeat seems to be a workaround for the short term

**Comment by Veldkornet** [comment]
> ![image](https://github.com/user-attachments/assets/c910e9b2-3d85-46e5-b7f4-ae6f39515a2c)
> 
> 
> 
> Enabling heartbeat in node red (under edit Server node) seems to be a workaround for the short term

Isn't this enabled by default with the add-on?
