### ISSUE TITLE
Node Red 3.1.2 spam in logs

### ISSUE THREAD

**Issue by Rudd-O** [zachowj/node-red-contrib-home-assistant-websocket#1241]
### Describe the bug

```
Jan 06 01:34:53 assistant Node-RED[3185848]: 6 Jan 01:34:53 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
Jan 06 01:34:53 assistant Node-RED[3185848]: 6 Jan 01:34:53 - [warn] Error
Jan 06 01:34:53 assistant Node-RED[3185848]:     at Object.evaluateJSONataExpression (/var/lib/node-red/node_modules/@node-red/util/lib/util.js:775:18)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at JSONataService.evaluate (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at ComparatorService.getComparatorResult (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/ComparatorService.js:47:91)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at CurrentStateController.onInput (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/current-state/CurrentStateController.js:48:102)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at CurrentStateController._InputOutputController_preOnInput (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/InputOutputController.js:62:76)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at /var/lib/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
Jan 06 01:34:53 assistant Node-RED[3185848]:     at Object.trigger (/var/lib/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at Node._emitInput (/var/lib/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at Node.emit (/var/lib/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at Node.receive (/var/lib/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:499:10)
Jan 06 01:34:53 assistant Node-RED[3185848]: 6 Jan 01:34:53 - [warn] Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author.
Jan 06 01:34:53 assistant Node-RED[3185848]: 6 Jan 01:34:53 - [warn] Error
Jan 06 01:34:53 assistant Node-RED[3185848]:     at Object.evaluateJSONataExpression (/var/lib/node-red/node_modules/@node-red/util/lib/util.js:775:18)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at JSONataService.evaluate (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/JSONataService.js:58:39)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at ComparatorService.getComparatorResult (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/services/ComparatorService.js:47:91)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at CurrentStateController.onInput (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/nodes/current-state/CurrentStateController.js:48:102)
Jan 06 01:34:53 assistant Node-RED[3185848]:     at CurrentStateController._InputOutputController_preOnInput (/var/lib/node-red/.node-red/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/InputOutputController.js:62:76)
```

### Expected behavior

No log spam.

### Example Flow

```json
Any flow with a current state node causes this.
```

### Environment Information

Version: latest

Home Assistant version: latest
Companion version: latest

Node-RED version: 3.1.2
Docker: no
Add-on: no

OS: Fedora 38

**Comment by zachowj** [comment]
Update your Home Assistant nodes
