### ISSUE TITLE
Websocket Connecting - Call-Service attempted without connection to server.

### ISSUE THREAD

**Issue by cezarq** [zachowj/node-red-contrib-home-assistant-websocket#209]
**Node-Red add-on LOG:**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 6.1.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / intel-nuc)
 Home Assistant Core: 0.106.0
 Home Assistant Supervisor: 201
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing...
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
audited 302 packages in 12.149s

13 packages are looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:46:31] INFO: Starting Node-RED...

> addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"

27 Feb 15:46:37 - [info] 

Welcome to Node-RED
===================

27 Feb 15:46:37 - [info] Node-RED version: v1.0.3
27 Feb 15:46:37 - [info] Node.js  version: v12.15.0
27 Feb 15:46:37 - [info] Linux 4.19.0-8-amd64 x64 LE
27 Feb 15:46:38 - [info] Loading palette nodes
Thu, 27 Feb 2020 18:46:52 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:955:30
27 Feb 15:46:54 - [info] Dashboard version 2.19.4 started at /endpoint/ui
Traceback (most recent call last):
  File "/opt/node_modules/node-red-node-pi-gpio/testgpio.py", line 4, in <module>
    import RPi.GPIO as GPIO
  File "/usr/lib/python2.7/site-packages/RPi/GPIO/__init__.py", line 23, in <module>
    from RPi._GPIO import *
RuntimeError: This module can only be run on a Raspberry Pi!
27 Feb 15:46:56 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
27 Feb 15:46:56 - [info] Settings file  : /etc/node-red/config.js
27 Feb 15:46:56 - [info] Context store  : 'default' [module=memory]
27 Feb 15:46:56 - [info] User directory : /config/node-red/
27 Feb 15:46:56 - [warn] Projects disabled : editorTheme.projects.enabled=false
27 Feb 15:46:56 - [info] Flows file     : /config/node-red/flows.json
27 Feb 15:46:56 - [info] Server now running at http://127.0.0.1:46836/
27 Feb 15:46:56 - [info] Starting flows
[15:46:56] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
27 Feb 15:46:59 - [info] Started flows
27 Feb 15:46:59 - [info] [mqtt-broker:mosquitto] Connected to broker: mqtt://192.168.5.246:1883
27 Feb 15:47:01 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
27 Feb 15:47:01 - [error] [server:Home Assistant] [object Object]
27 Feb 15:47:06 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
27 Feb 15:47:09 - [warn] [telegrambot-config:7374c476.f2f0bc] ETELEGRAM: 409 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
27 Feb 15:47:09 - [warn] [telegrambot-config:7374c476.f2f0bc] Unknown error. Trying again.
27 Feb 15:47:10 - [error] [api-call-service:Umidade Solo do Jardim] Call-Service attempted without connection to server.
27 Feb 15:47:12 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
27 Feb 15:47:17 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
```

**System Log**:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 117, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/proxy.py", line 201, in websocket
    client = await self._websocket_client()
  File "/usr/src/hassio/hassio/api/proxy.py", line 112, in _websocket_client
    url, heartbeat=30, verify_ssl=False
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 738, in _ws_connect
    headers=resp.headers)
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='https://172.30.32.1:8123/api/websocket
20-02-27 19:19:20 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished coro=<WebSocketWriter.ping() done, defined at /usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py:631> exception=RuntimeError('unable to perform operation on <TCPTransport closed=True reading=False 0x55c7e1016860>; the handler is closed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 635, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_websocket.py", line 617, in _send_frame
    self.transport.write(header + message)
  File "uvloop/handles/stream.pyx", line 673, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 159, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x55c7e1016860>; the handler is closed
20-02-27 19:19:20 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
20-02-27 19:19:20 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
20-02-27 19:19:21 ERROR (MainThread) [aiohttp.server] Error handling request
```

**Comment by zachowj** [comment]
Go into to server config and make sure the `I use the Home Assistant Add-on` is checked.

![image](https://user-images.githubusercontent.com/37859597/75520931-88f90900-59bb-11ea-8e20-7a8d52c4646b.png)

**Comment by cezarq** [comment]
This is checked by default in 6.1.1 HA node-red addon version, so is checked with the issue still happing!

**Comment by cezarq** [comment]
> Go into to server config and make sure the `I use the Home Assistant Add-on` is checked.
> 
> ![image](https://user-images.githubusercontent.com/37859597/75520931-88f90900-59bb-11ea-8e20-7a8d52c4646b.png)

This is checked by default in 6.1.1 HA node-red addon version, so is checked with the issue still happing!

**Comment by zachowj** [comment]
When you uncheck it and the Base URL and Access Token fields appear is there a value in the Access Token Field?

![image](https://user-images.githubusercontent.com/37859597/75542083-f1ec7b00-59d3-11ea-8d4b-e0dd94170249.png)

The HA logs show that NR is passing in an invalid access token but it should be automatically populated by an environment variable. I'm guessing you have tried restarting?

**Comment by cezarq** [comment]
> When you uncheck it and the Base URL and Access Token fields appear is there a value in the Access Token Field?
> 
> ![image](https://user-images.githubusercontent.com/37859597/75542083-f1ec7b00-59d3-11ea-8d4b-e0dd94170249.png)
> 
> The HA logs show that NR is passing in an invalid access token but it should be automatically populated by an environment variable. I'm guessing you have tried restarting?

When uncheck shows the base URL (http://supervisor/core) and the access token has a value.
I already tried to restart the HA and the OS without success!

**Comment by zachowj** [comment]
Try this flow: https://pastebin.com/SY9UWtFY

After deploying the first time you should see something like
![image](https://user-images.githubusercontent.com/37859597/75607759-3ef14f80-5aaf-11ea-93e5-1f3e6c84dc92.png)

Then click the inject node "get config" and you should see

![image](https://user-images.githubusercontent.com/37859597/75607795-7f50cd80-5aaf-11ea-872f-3af6891e28b4.png)

**Comment by cezarq** [comment]
> Try this flow: https://pastebin.com/SY9UWtFY
> 
> After deploying the first time you should see something like
> ![image](https://user-images.githubusercontent.com/37859597/75607759-3ef14f80-5aaf-11ea-93e5-1f3e6c84dc92.png)
> 
> Then click the inject node "get config" and you should see
> 
> ![image](https://user-images.githubusercontent.com/37859597/75607795-7f50cd80-5aaf-11ea-872f-3af6891e28b4.png)

I fixed my issue by restoring a snapshot to the previous working version (105.5), heading into the Configuration node of Home Assistant in NR, checking the box "I use the HA Addon", and then upgrading to the latest NR.  For whatever reason, if you don't check that checkbox before upgrading, it doesn't seem to want to listen to that checkbox post upgrade.
