### ISSUE TITLE
Nodered docker container running but not accessible

### ISSUE THREAD

**Issue by Bodge-IT** [zachowj/node-red-contrib-home-assistant-websocket#249]
### Describe the bug
Error from log:
30 Jun 08:03:12 - [info] [server:Animus] WebSocket Connected to https://******:8123
(node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'timeSinceChangedMs' on string 'On'
    at ServerStateChangedNode.onHaEventsStateChanged (/data/node_modules/node-red-contrib-home-assistant-websocket/nodes/events-state-changed/events-state-changed.js:59:48)
    at HaWebsocket.emit (events.js:198:13)
    at HaWebsocket.EventEmitter.emit (domain.js:448:20)
    at HaWebsocket.onClientEvents (/data/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:244:26)
    at Object.unsubCallback.(anonymous function).client.subscribeEvents [as callback] (/data/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:172:31)
    at o._handleMessage (/data/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:2797)
    at WebSocket.<anonymous> (/data/node_modules/home-assistant-js-websocket/dist/haws.umd.js:1:885)
    at WebSocket.onMessage (/data/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.EventEmitter.emit (domain.js:448:20)
    at Receiver.receiverOnMessage (/data/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.EventEmitter.emit (domain.js:448:20)
    at Receiver.dataMessage (/data/node_modules/ws/lib/receiver.js:436:14)
    at perMessageDeflate.decompress (/data/node_modules/ws/lib/receiver.js:393:23)
    at _decompress (/data/node_modules/ws/lib/permessage-deflate.js:306:9)
    at _inflate.flush (/data/node_modules/ws/lib/permessage-deflate.js:385:7)
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:548:8)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
30 Jun 08:03:15 - [error] [docker:cea7896.2d202f8] Error during client.getEvents()
30 Jun 08:03:15 - [error] [docker:b745fadb.b3732] Error during client.getEvents()
30 Jun 08:05:21 - [error] [docker:60bada44.fd4354] Error during client.getEvents()

### To Reproduce

docker restart nodered
docker logs nodered

### Expected behavior
On warnings, still allow Nodered access

### Environment (please complete the following information):
Homeassistant 0.112b3
Node-RED version: v1.0.2
Node.js  version: v10.16.3
node-red-contrib-home-assistant-websocket: v22.3 tried to update via npm but still at 22.3
Nodered Companion from hacs 0.4.4
Nodered running in docker on Pi

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

**Comment by zachowj** [comment]
Is this reproducible every time?

**Comment by Bodge-IT** [comment]
Hi @zachowj Jason, my apologies, forgot I'd left this open.  It was repeatable for a week then miraculously one day, came back.  I took the opportunity to upgrade the node and no longer see the issue.  I think an update to HA in between may have freed it up.
