### ISSUE TITLE
more null state on event change crashes in v0.27.6

### ISSUE THREAD

**Issue by b3nj1** [zachowj/node-red-contrib-home-assistant-websocket#297]
### Describe the bug

Hi @zachowj ,
I've been using v0.27.6 version for a couple of days, and last night, I got another invalid new state exception below. It caused node-red to crash.

```
    Exception:
3 Dec 23:43:49 - TypeError: Cannot read property 'state' of null
    at ServerStateChangedNode.output (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/events-state-changed/events-state-changed.js:206:55)
    at ServerStateChangedNode.onHaEventsStateChanged (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/events-state-changed/events-state-changed.js:141:22)
    at HaWebsocket.emit (events.js:327:22)
    at HaWebsocket.onClientEvents (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:290:22)
    at Object.callback (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:229:31)
    at Connection._handleMessage (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:353:26)
    at WebSocket.<anonymous> (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:191:57)
    at WebSocket.onMessage (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:825:20)
npm ERR! code ELIFECYCLE
```
### To Reproduce

It's not clear which entity triggered this from the logs.

### Expected behavior

No crash.

### Example Flow

```
export goes here
```

### Environment (please complete the following information):

3 Dec 23:43:53 - [info] Node-RED version: v1.2.5
3 Dec 23:43:53 - [info] Node.js  version: v12.18.4
- NR Home Assistant Plugin Version: [e.g. 0.4.4]
- Is Node Red running in Docker: [eHA addon]
- Node Red add-on Version: [7.2.11]
   - override to: node-red-contrib-home-assistant-websocket [v0.27.6]

### Other (please complete the following information):

- Have you searched previous issues for duplicates?:

**Comment by zachowj** [comment]
Your HA instance must be throwing some weird state change events because I don't know how it fires a state change event when there's no `new_state`.

**Comment by b3nj1** [comment]
Yeah, it seems to be the iOS home assistant app. Occasionally it uses the
wrong entity name it seems. :(
