### ISSUE TITLE
Crash from regex-using node during HA entity change

### ISSUE THREAD

**Issue by OttPeterR** [zachowj/node-red-contrib-home-assistant-websocket#340]
### Describe the bug

The affected nodes are both the "events: state" and "trigger: state" nodes if they are using the regex option for specifying entity ID. These nodes will cause a soft crash if the entities the query returns are null at the time, thus having no "state" attribute. This seems to happen when entities are newly created in HA such as from browser_mod or refreshing HA groups.

### To Reproduce

1. Place a "trigger: state" node
2. Edit it, set to regex, enter in: .*
3. Deploy flow
4. In HA > configuration > server controls > click on "RELOAD GROUPS, GROUP ENTITIES, AND GROUP NOTIFY SERVICES"
5. Crash 

### Expected behavior

Not crash if "state" attribute is not present. A simple check should fix it :)

### Screenshots

none

### Example Flow

none

### Environment (please complete the following information):

- Node Red Version: 1.2.5
- Node.js Version: 12.18.4
- NR Home Assistant Plugin Version: 0.4.4
- Is Node Red running in Docker: HA addon

### Other (please complete the following information):

This seems similar to issue #301

### Additional context

Logs

21 Jan 00:59:54 - [red] Uncaught Exception:
21 Jan 00:59:54 - TypeError: Cannot read property 'state' of null
    at ServerStateChangedNode.isEventValid (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/events-state-changed/events-state-changed.js:291:41)
    at ServerStateChangedNode.onHaEventsStateChanged (/opt/node_modules/node-red-contrib-home-assistant-websocket/nodes/events-state-changed/events-state-changed.js:66:23)
    at HaWebsocket.emit (events.js:327:22)
    at HaWebsocket.onClientEvents (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:290:22)
    at Object.callback (/opt/node_modules/node-red-contrib-home-assistant-websocket/lib/ha-websocket.js:229:31)
    at Connection._handleMessage (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:353:26)
    at WebSocket.<anonymous> (/opt/node_modules/home-assistant-js-websocket/dist/haws.cjs:191:57)
    at WebSocket.onMessage (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/receiver.js:437:14)
    at /opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/receiver.js:394:23
    at /opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/permessage-deflate.js:306:9
    at /opt/node_modules/node-red-contrib-home-assistant-websocket/node_modules/ws/lib/permessage-deflate.js:385:7
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8)

**Comment by zachowj** [comment]
A current workaround would be to use an events: all node using the `state_changed` as the event type.

**Comment by OttPeterR** [comment]
This is fixed for me in the recent Node-RED add-on v8.0.0 update
