### ISSUE TITLE
Error fetching node id's when editing node

### ISSUE THREAD

**Issue by agarity** [zachowj/node-red-contrib-home-assistant-websocket#45]
**Describe the bug**
When editing a node, a error is displayed:
TypeError: Cannot read property 'getEntities' of undefined
    at ConfigServerNode.getEntities (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/nodes/config-server/config-server.js:9:18)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/node-red/red/api/auth/index.js:63:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/application.js:233:9
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:635:15
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:260:14)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)

And consequently autofill on entity id is not working.

**To Reproduce**
Open a node containing a entity id field such as current state
Error will be displayed in the notification area of node-red and auto fill will not work.

**Expected behavior**
When editing a node that utilizes entity id, the entity id field should auto populate as you type and an error should not be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/45503741/49323558-ec06a200-f4d1-11e8-98e5-a0fa4869208e.png)

**Example Flow**
[{"id":"142aede4.c4e932","type":"api-current-state","z":"b9288163.54493","name":"test","server":"dccd1a65.3b5848","halt_if":"","override_topic":true,"override_payload":true,"override_data":true,"entity_id":"sun.sun","x":470,"y":700,"wires":[[]]},{"id":"30bafbbe.785ce4","type":"inject","z":"b9288163.54493","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":700,"wires":[["142aede4.c4e932"]]},{"id":"dccd1a65.3b5848","type":"server","z":"","name":"HA01","legacy":false,"hassio":false,"rejectUnauthorizedCerts":true}]

**Environment (please complete the following information):**
 - Node Red Version: 0.18.5
 - NR Home Assistant Plugin Version: 0.3.1
 - Is Node Red running in Docker: no
 - Home Assistant version: 0.83.2

**Other (please complete the following information):**
- Have you searched previous issues for duplicates?: Yes - there were previous reports of entity id field not auto filling however bug did not seem to match this behavior.
- Did you attempt to reproduce the issue in the dev docker environment, if so what were results (See README.md): Did not attempt

**Additional context**
Add any other context about the problem here.  Everything was running fine pre Home Assistant 0.83.X upgrade (Received 0.83.1 first, which had problems with auth and 0.83.2 was recieved a few hours later which resolved those issues.)

Using token auth with home assistant.  Not using api_password

Call service node edit also has an issue auto populating the service/entity id fields with autofill. and 2 errors are displayed:

TypeError: Cannot read property 'getServices' of undefined
    at ConfigServerNode.getServices (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/nodes/config-server/config-server.js:21:18)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/node-red/red/api/auth/index.js:63:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/application.js:233:9
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:635:15
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:260:14)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)

TypeError: Cannot read property 'getEntities' of undefined
    at ConfigServerNode.getEntities (/home/pi/.node-red/node_modules/node-red-contrib-home-assistant-websocket/nodes/config-server/config-server.js:9:18)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/node-red/red/api/auth/index.js:63:13
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/application.js:233:9
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:635:15
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:260:14)
    at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)

**Comment by agarity** [comment]
Well that was quick, please close the bug - looks like something happened during home assistant upgrade.  Completely restarting node-red (versus full deploy) corrected the problem.  I am no longer able to reproduce it.
