### ISSUE TITLE
Event nodes always “Connecting” but otherwise work

### ISSUE THREAD

**Issue by bwims** [zachowj/node-red-contrib-home-assistant-websocket#641]
### Describe the bug

I have two node red servers, both running node-red-contrib-home-assistant-websocket .
One is on the same server as Home Assistant. All 3 systems are in Docker containers in host network mode.

Home Assistant has node red integration.

The system that shares the same server, specifying home assistant as the same ip address shows event nodes as running, unless they show the last value returned.

The other system shows the event nodes as “connecting”, yet they do return values, and then return to “connecting”.

Can anyone recognise this problem, and if so, if there is a way to fix it?

Thanks!

Brian

### To Reproduce

1 Create instance of event node
2 enter the entity id of an active sensor
3 exit and deploy

On one server the node will have a green status of "Running" until a value is transmitted from the sensor.

On the other, the node will have a yellow status of "Connecting"  until a value is transmitted from the sensor when it will very briefly cycle through "connected", "running", display of value, "connecting".

### Expected behavior

I expect both servers to exhibit the same behaviour.

### Screenshots

Server 1 - All the time:
![image](https://user-images.githubusercontent.com/18516073/172918042-cdd542b8-8101-4d5f-9c4f-6b98b19294b5.png)

Server 2 - before a value transmitted
![image](https://user-images.githubusercontent.com/18516073/172918137-9255ce97-9b09-4897-86d6-74e49c77e600.png)

Server 2 - after a value transmitted (very briefly)
![image](https://user-images.githubusercontent.com/18516073/172918225-a88150d1-7707-4188-81c1-67ec5a1dc38a.png)

Serve 2- Soon afterwards 
![image](https://user-images.githubusercontent.com/18516073/172918137-9255ce97-9b09-4897-86d6-74e49c77e600.png)

### Example Flow

```json
Server 1
[
    {
        "id": "5ddc7929a1fc5ce0",
        "type": "server-state-changed",
        "z": "dae4e7af.da4ef8",
        "name": "CaravanPHT T",
        "server": "d3a7a1a2ec374919",
        "version": 4,
        "exposeToHomeAssistant": false,
        "haConfig": [
            {
                "property": "name",
                "value": ""
            },
            {
                "property": "icon",
                "value": ""
            }
        ],
        "entityidfilter": "sensor.caravan_pht_bme280_temperature",
        "entityidfiltertype": "exact",
        "outputinitially": false,
        "state_type": "str",
        "haltifstate": "",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "outputs": 1,
        "output_only_on_state_change": true,
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "ignorePrevStateNull": false,
        "ignorePrevStateUnknown": false,
        "ignorePrevStateUnavailable": false,
        "ignoreCurrentStateUnknown": false,
        "ignoreCurrentStateUnavailable": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "eventData"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            }
        ],
        "x": 120,
        "y": 160,
        "wires": [
            []
        ]
    },
    {
        "id": "d3a7a1a2ec374919",
        "type": "server",
        "name": "Home Assistant",
        "version": 2,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30"
    }
]

Server 2 

[
    {
        "id": "0e33d6d380f50acb",
        "type": "server-state-changed",
        "z": "ef7bca265ac36c58",
        "name": "lux",
        "server": "bb97bd2097fb0698",
        "version": 4,
        "exposeToHomeAssistant": false,
        "haConfig": [
            {
                "property": "name",
                "value": ""
            },
            {
                "property": "icon",
                "value": ""
            }
        ],
        "entityidfilter": "sensor.lightsensor_bh1750_illuminance",
        "entityidfiltertype": "exact",
        "outputinitially": true,
        "state_type": "num",
        "haltifstate": "",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "outputs": 1,
        "output_only_on_state_change": true,
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "ignorePrevStateNull": false,
        "ignorePrevStateUnknown": false,
        "ignorePrevStateUnavailable": false,
        "ignoreCurrentStateUnknown": false,
        "ignoreCurrentStateUnavailable": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "eventData"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            }
        ],
        "x": 130,
        "y": 120,
        "wires": [
            [
                "695e7309ecb5ab11"
            ]
        ]
    },
    {
        "id": "695e7309ecb5ab11",
        "type": "change",
        "z": "ef7bca265ac36c58",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "lux",
                "pt": "flow",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 310,
        "y": 120,
        "wires": [
            [
                "84fd6064e2b72ed6"
            ]
        ]
    },
    {
        "id": "b5b8406fbe602c45",
        "type": "api-current-state",
        "z": "ef7bca265ac36c58",
        "name": "Light Sensor Check",
        "server": "bb97bd2097fb0698",
        "version": 3,
        "outputs": 1,
        "halt_if": "",
        "halt_if_type": "num",
        "halt_if_compare": "is",
        "entity_id": "sensor.lightsensor_bh1750_illuminance",
        "state_type": "str",
        "blockInputOverrides": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "override_topic": false,
        "state_location": "payload",
        "override_payload": "msg",
        "entity_location": "data",
        "override_data": "msg",
        "x": 390,
        "y": 60,
        "wires": [
            [
                "f22b43a3fd808a9d"
            ]
        ]
    },
    {
        "id": "e35426d6fc3df3e6",
        "type": "inject",
        "z": "ef7bca265ac36c58",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "60",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 60,
        "wires": [
            [
                "b5b8406fbe602c45"
            ]
        ]
    },
    {
        "id": "bb97bd2097fb0698",
        "type": "server",
        "name": "Home Assistant",
        "version": 2,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30"
    }
]
```

### This package's version (not the Home Assistant add-on version)

0.43.1

### Is Node-RED running in Docker?

Yes

### Node-RED version

2.2.2

### Node.js version

v14.18.2

**Comment by bwims** [comment]
I noticed that this condition was associated with the following error in the HA log:
`2022-06-10 15:02:59 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
`

However. after stopping and starting, the condition appears to have cleared itself!
