### ISSUE TITLE
Error: Cannot find module 'joi'

### ISSUE THREAD

**Issue by phdelodder** [zachowj/node-red-contrib-home-assistant-websocket#65]
Using docker container nodered/node-red-docker:0.19.5-rpi-v8 for arm64 I get the following error: 

```
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/server] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/server-events] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/server-state-changed] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/trigger-state] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/poll-state] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/api-call-service] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/ha-fire-event] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/api-current-state] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/ha-get-entities] Error: Cannot find module 'joi'
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/api-get-history] Error: Cannot find module 'joi' (line:1)
28 Dec 16:14:34 - [warn] [node-red-contrib-home-assistant-websocket/api-render-template] Error: Cannot find module 'joi' (line:1)
```

**Comment by zachowj** [comment]
Is this after a new docker build? Because it looks like the npm package just didn't get installed. What do your build logs show?

**Comment by phdelodder** [comment]
I had before and after the new docker build. Where can I get the build logs?

**Comment by TimorTartakovsky** [comment]
After switching from 'joi' library to '@hapi/joi' the following exception is appear:

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\git\codemotion\api\node_modules\express-validation\lib\index.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\git\codemotion\api\dist\initializers\express.js:61:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\git\codemotion\api\dist\index.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by a-m-dev** [comment]
any help ??? 
Same here

**Comment by zachowj** [comment]
It's probably an npm error reinstall the package.
