### ISSUE TITLE
Installation problem on Raspberry pi

### ISSUE THREAD

**Issue by ir-fuel** [zachowj/node-red-contrib-home-assistant-websocket#69]
**Describe the bug**
npm install fails

**To Reproduce**
Run `npm install`

**Expected behavior**
The package should be installed

**Environment (please complete the following information):**

- Node Red Version: 0.19.5
- NR Home Assistant Plugin Version:  0.5.1
- Is Node Red running in Docker: no

**Additional context**

This is what I get:
```
npm install node-red-contrib-home-assistant-websocket
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! path /home/pi/.node-red/node_modules/.date-fns.DELETE/difference_in_calendar_iso_weeks
npm ERR! code Unknown system error -117
npm ERR! errno -117
npm ERR! syscall unlink
npm ERR! Unknown system error -117: Unknown system error -117, unlink '/home/pi/.node-red/node_modules/.date-fns.DELETE/difference_in_calendar_iso_weeks'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-02T16_49_58_473Z-debug.log
```

**Comment by walthowd** [comment]
Can you post the full log and your node version (node -v)? What happens if you rm -rf /home/pi/.node-red/node_modules/.date-fns.DELETE/ and install again?

**Comment by ir-fuel** [comment]
This is actually the full log.

the `rm` command results in:

```
rm -rf /home/pi/.node-red/node_modules/.date-fns.DELETE/
rm: cannot remove '/home/pi/.node-red/node_modules/.date-fns.DELETE/difference_in_calendar_days/index.js.flow': Structure needs cleaning
rm: cannot remove '/home/pi/.node-red/node_modules/.date-fns.DELETE/difference_in_calendar_iso_weeks': Structure needs cleaning
rm: cannot remove '/home/pi/.node-red/node_modules/.date-fns.DELETE/are_ranges_overlapping/index.d.ts': Structure needs cleaning
```

**Comment by walthowd** [comment]
"Structure needs cleaning" indicates file system corruption. Please try a fsck on your volume and try the delete again.

**Comment by ir-fuel** [comment]
Ok that solved it, but now I have the same issue as in the original repo:

```
npm install node-red-contrib-home-assistant-websocket

> bcrypt@1.0.3 install /home/pi/.node-red/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(502): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.15.0 (node-v64 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/.node-red/node_modules/bcrypt/build'
make: Entering directory '/home/pi/.node-red/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
rm: cannot remove './Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw': No such file or directory
bcrypt_lib.target.mk:101: recipe for target 'Release/obj.target/bcrypt_lib/src/blowfish.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/pi/.node-red/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/pi/.node-red/node_modules/bcrypt
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/.node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/pi/.node-red/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.14.79-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/.node-red/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/.node-red/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/.node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/pi/.node-red/node_modules/bcrypt/lib/binding' (1)
../src/bcrypt.cc:52:22: fatal error: node_blf.h: No such file or directory
compilation terminated.
bcrypt_lib.target.mk:101: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/bcrypt/build'
 ERR! build error ....] - postinstall: info lifecycle node-red-contrib-home-assistant-websocket@0.5.1~postinstall: node-red-contrib-home-assistant-websocket@0.5.1
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/pi/.node-red/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/pi/.node-red/node_modules/bcrypt
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 (node_modules/bcrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-red-contrib-home-assistant-websocket@0.5.1
added 11 packages from 10 contributors and audited 2484 packages in 49.183s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by zachowj** [comment]
looks like your missing build tools try:

`sudo apt-get install build-essential`

**Comment by ir-fuel** [comment]
They are all installed.
I've taken this to the bcrypt repo, als it's the bcrypt install that fails, and installing it on its own using `npm install bcrypt` also fails with compile errors.

See https://github.com/kelektiv/node.bcrypt.js/issues/694
