### ISSUE TITLE
Switch states not preserved after HA restart, all switches turn on 

### ISSUE THREAD

**Issue by MaxVonEvil** [zachowj/node-red-contrib-home-assistant-websocket#973]
## Version of the custom_component: 1.4.0

```
 Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 18:07:25 (32 occurrences)
Last logged: 18:17:45

    Exception in handle_entity_update when dispatching 'nodered_entity_f3597401.3f5758_7e9f13ec224fa3d8': ({'type': 'nodered/entity', 'server_id': 'f3597401.3f5758', 'node_id': '7e9f13ec224fa3d8', 'state': 'Ok', 'attributes': {}, 'id': 1094},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 590, in state numerical_value = int(value) ^^^^^^^^^^ ValueError: invalid literal for int() with base 10: 'Ok' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 146, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state raise ValueError( ValueError: Sensor sensor.smartups_battery_life has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Ok' (<class 'str'>)
    Exception in handle_entity_update when dispatching 'nodered_entity_f3597401.3f5758_7e9f13ec224fa3d8': ({'type': 'nodered/entity', 'server_id': 'f3597401.3f5758', 'node_id': '7e9f13ec224fa3d8', 'state': 'Ok', 'attributes': {}, 'id': 1124},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 590, in state numerical_value = int(value) ^^^^^^^^^^ ValueError: invalid literal for int() with base 10: 'Ok' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 146, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state raise ValueError( ValueError: Sensor sensor.smartups_battery_life has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Ok' (<class 'str'>)
    Exception in handle_entity_update when dispatching 'nodered_entity_f3597401.3f5758_7e9f13ec224fa3d8': ({'type': 'nodered/entity', 'server_id': 'f3597401.3f5758', 'node_id': '7e9f13ec224fa3d8', 'state': 'Ok', 'attributes': {}, 'id': 1154},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 590, in state numerical_value = int(value) ^^^^^^^^^^ ValueError: invalid literal for int() with base 10: 'Ok' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 146, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state raise ValueError( ValueError: Sensor sensor.smartups_battery_life has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Ok' (<class 'str'>)
    Exception in handle_entity_update when dispatching 'nodered_entity_f3597401.3f5758_7e9f13ec224fa3d8': ({'type': 'nodered/entity', 'server_id': 'f3597401.3f5758', 'node_id': '7e9f13ec224fa3d8', 'state': 'Ok', 'attributes': {}, 'id': 1193},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 590, in state numerical_value = int(value) ^^^^^^^^^^ ValueError: invalid literal for int() with base 10: 'Ok' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/nodered/__init__.py", line 146, in handle_entity_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state raise ValueError( ValueError: Sensor sensor.smartups_battery_life has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Ok' (<class 'str'>) 
```

## Describe the bug

After upgrading about 3 days ago to Node Red Compagnion 1.4.0 I noticed that after HA restart, any switches defined in Node-red would turn on. Others would become unresponsive, as if something is broken between HA and NodeRed, specifically if you try to turn off a switch node-red it would fail and revert to the on-state.

HA details:
Home Assistant 2023.7.0 
Supervisor 2023.07.1 
Operating System 10.3 
Frontend 20230705.0 - latest

**Comment by MaxVonEvil** [comment]
> @MaxVonEvil While in NR you can use the “Search flows” command and enter the id `7e9f13ec224fa3d8` and it will show you the nodes that match. I'm 99% certain those errors are from a sensor node.

You are right, that was actually a sensor node. As stated those still seem to work.


> The switch node code hasn't changed in [10 months](https://github.com/zachowj/hass-node-red/blob/main/custom_components/nodered/switch.py), maybe something changed on the HA side. I'll have to see if I can replicate it.

Thanks, it's unfortunatly not the first time and likely not the last time HA's unintentionally broken an integration with an underlying change. I'll unfortunately have to continue to covert 30-something switches to input_boolean. Yay.

**Comment by zachowj** [comment]
@MaxVonEvil it's fixed in 0.51.1

**Comment by MaxVonEvil** [comment]
@zachowj Pardon, not sure which component that refers to?

**Comment by zachowj** [comment]
node-red-contrib-home-assistant-websocket

**Comment by MaxVonEvil** [comment]
Got it. Updated and confirmed it's working again. Thanks for the help!

**Comment by goofy1988** [comment]
Nice to hear that there is a fix. Ive tried to manually update the websocket nodes in the node red paletteanager but there is still only version 0.51.0. Can i do an update over the terminal or how can i force an update? A restart of node red and HA still only show the .0 version.

Thanks for your help.
